version: '2'
services:
    fafi-app:
        image: fafi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fafi-mysql:3306/fafi?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fafi-mysql:
        extends:
            file: mysql.yml
            service: fafi-mysql
